apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - cronjob.yaml
  - rbac.yaml

secretGenerator:
  - name: generate-nodes-secrets
    envs:
      - secrets.env

images:
  - name: generate-nodes
    newTag: latest
